@extends('layouts.app')

@section('title', 'Administrator Dashboard')

@section('page-title', 'Administrator Dashboard')

@section('content')

    <section class="page-header">
        <div class="page-header-copy">
            <h2>
                Welcome back,
                {{ auth()->user()->name }}
            </h2>

            <p>
                Monitor projects, manage users, review assessment
                progress, and access the main system functions.
            </p>
        </div>

        <div class="page-actions">
            <a
                href="{{ route('projects.index') }}"
                class="button button-secondary"
            >
                View Projects
            </a>

            <a
                href="{{ route('projects.create') }}"
                class="button button-primary"
            >
                + Create Project
            </a>
        </div>
    </section>

    {{-- System statistics --}}
    <section
        class="metric-grid"
        aria-label="System statistics"
    >
        <article class="metric-card">
            <p class="metric-label">
                Total Projects
            </p>

            <p class="metric-value">
                {{ $statistics['total_projects'] ?? 0 }}
            </p>

            <p class="metric-helper">
                Projects registered in the system
            </p>
        </article>

        <article class="metric-card">
            <p class="metric-label">
                Completed Assessments
            </p>

            <p class="metric-value">
                {{ $statistics['completed_projects'] ?? 0 }}
            </p>

            <p class="metric-helper">
                Projects with completed assessments
            </p>
        </article>

        <article class="metric-card">
            <p class="metric-label">
                Assessment Reports
            </p>

            <p class="metric-value">
                {{ $statistics['total_reports'] ?? 0 }}
            </p>

            <p class="metric-helper">
                Reports generated by the system
            </p>
        </article>

        <article class="metric-card">
            <p class="metric-label">
                Active Users
            </p>

            <p class="metric-value">
                {{ $statistics['active_users'] ?? 0 }}
            </p>

            <p class="metric-helper">
                Users who can access the system
            </p>
        </article>
    </section>

    <div class="form-grid">

        {{-- Quick actions --}}
        <section class="panel">
            <div class="panel-header">
                <div>
                    <h2>Quick Actions</h2>
                </div>

                <span class="status-badge status-success">
                    System Active
                </span>
            </div>

            <div class="panel-body">
                <div class="page-actions">
                    <a
                        href="{{ route('projects.create') }}"
                        class="button button-primary"
                    >
                        + New Project
                    </a>

                    <a
                        href="{{ route('admin.users.create') }}"
                        class="button button-secondary"
                    >
                        + New User
                    </a>

                    <a
                        href="{{ route('admin.users.index') }}"
                        class="button button-secondary"
                    >
                        Manage Users
                    </a>
                </div>
            </div>
        </section>

        {{-- Assessment workflow --}}
        <section class="panel">
            <div class="panel-header">
                <div>
                    <h2>Assessment Workflow</h2>
                </div>
            </div>

            <div class="panel-body">
                <div class="table-container">
                    <table class="data-table">
                        <tbody>
                            <tr>
                                <td>
                                    <strong>1. Project Registration</strong>
                                </td>

                                <td>
                                    <span
                                        class="status-badge status-success"
                                    >
                                        Available
                                    </span>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <strong>2. Data Ingestion</strong>
                                </td>

                                <td>
                                    <span
                                        class="status-badge status-warning"
                                    >
                                        Next Module
                                    </span>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <strong>3. Impact Assessment</strong>
                                </td>

                                <td>
                                    <span
                                        class="status-badge status-success"
                                    >
                                        Available
                                    </span>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <strong>4. Manager Approval</strong>
                                </td>

                                <td>
                                    <span
                                        class="status-badge status-success"
                                    >
                                        Available
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div>

    {{-- Recent projects --}}
    <section
        class="panel"
        style="margin-top: 22px;"
    >
        <div class="panel-header">
            <div>
                <h2>Recent Projects</h2>
            </div>

            <a
                href="{{ route('projects.index') }}"
                class="button button-secondary"
            >
                View All
            </a>
        </div>

        <div class="table-container">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Project Code</th>
                        <th>Project Title</th>
                        <th>Sector</th>
                        <th>Status</th>
                        <th>Created</th>
                        <th>Action</th>
                    </tr>
                </thead>

                <tbody>
                    @forelse(
                        ($recentProjects ?? collect())
                        as $project
                    )
                        <tr>
                            <td>
                                <strong>
                                    {{ $project->project_code }}
                                </strong>
                            </td>

                            <td>
                                {{ $project->title }}
                            </td>

                            <td>
                                {{ $project->sector ?? 'Not provided' }}
                            </td>

                            <td>
                                @php
                                    $statusClass = match (
                                        $project->status
                                    ) {
                                        'completed' =>
                                            'status-success',

                                        'in_progress' =>
                                            'status-warning',

                                        default =>
                                            'status-neutral',
                                    };
                                @endphp

                                <span
                                    class="status-badge
                                        {{ $statusClass }}"
                                >
                                    {{
                                        ucfirst(
                                            str_replace(
                                                '_',
                                                ' ',
                                                $project->status
                                            )
                                        )
                                    }}
                                </span>
                            </td>

                            <td>
                                {{
                                    $project->created_at
                                        ?->format('d M Y')
                                }}
                            </td>

                            <td>
                                <a
                                    href="{{
                                        route(
                                            'projects.show',
                                            $project
                                        )
                                    }}"
                                    class="button button-secondary"
                                >
                                    Open
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6">
                                No recent project information is
                                available yet.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </section>

@endsection
